### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by zhouzhuojie** [openflagr/flagr-archived#14]
Currently, when we cut a new release, we need to follow these steps:

- Update browser/flagr-ui/package.json with the new version bump
- Update browser/flagr-ui/package-lock.json with the new version bump
- Update swagger/index.yaml with the new version
- Run `make gen` to update all the generated files (e.g. `swagger_gen/*`, `docs/api_docs/*`)

**Comment by pixeldrew** [comment]
can I suggest integrating [semantic-release](https://github.com/semantic-release/semantic-release) using github actions?
